(defvar myemacs-dir (file-name-directory load-file-name))
(defvar languages-dir (concat myemacs-dir "languages/"))
(defvar modules-dir (concat myemacs-dir "modules/"))
(defvar vendor-dir (concat myemacs-dir "vendor/"))

(add-to-list 'load-path languages-dir)
(add-to-list 'load-path modules-dir)
(add-to-list 'load-path vendor-dir)

(require 'core)
(require 'editor)
(require 'keybindings)
(require 'ui)

(require 'lang-c)
(require 'lang-dtrace)
(require 'lang-js)
(require 'lang-markdown)
(require 'lang-sql)
(require 'lang-xml)

(require 'multi-web-mode)
(setq mweb-default-major-mode 'html-mode)
(setq mweb-tags '((php-mode "<\\?php\\|<\\? \\|<\\?=" "\\?>")
		  (js-mode "<script +\\(type=\"text/javascript\"\\|language=\"javascript\"\\)[^>]*>" "</script>")
		  (css-mode "<style +type=\"text/css\"[^>]*>" "</style>")))
(setq mweb-filename-extensions '("php" "htm" "html" "ctp" "phtml" "php4" "php5"))
(multi-web-global-mode 1)